FROM golang:latest AS builder

WORKDIR /usr/src/app

RUN go mod init main

COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM scratch
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/app .

CMD [ "./app" ]
